// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdw42QorBAQsvinbIFWvyQclIRMCIV5Lk',
    appId: '1:824197507820:web:f3fb3e9c92d553563113c9',
    messagingSenderId: '824197507820',
    projectId: 'kitpool-34338',
    authDomain: 'kitpool-34338.firebaseapp.com',
    storageBucket: 'kitpool-34338.appspot.com',
    measurementId: 'G-7DYVDNM61E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPLkohBTdQwhuQUhUpFD3F6MID0S_U6ZE',
    appId: '1:824197507820:android:74013623bc9a11643113c9',
    messagingSenderId: '824197507820',
    projectId: 'kitpool-34338',
    storageBucket: 'kitpool-34338.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgELQP0MPAZ1S51ErszUvBIoy3s4s0zDc',
    appId: '1:824197507820:ios:bdad9b4330a774133113c9',
    messagingSenderId: '824197507820',
    projectId: 'kitpool-34338',
    storageBucket: 'kitpool-34338.appspot.com',
    iosClientId: '824197507820-p2vhiga9bteie9vdivrnhhqoaehmvtof.apps.googleusercontent.com',
    iosBundleId: 'com.example.animatedBottomAppBar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgELQP0MPAZ1S51ErszUvBIoy3s4s0zDc',
    appId: '1:824197507820:ios:550215dc9a8415783113c9',
    messagingSenderId: '824197507820',
    projectId: 'kitpool-34338',
    storageBucket: 'kitpool-34338.appspot.com',
    iosClientId: '824197507820-1n6mg6cbdn8sfglbbu6e6pac56tt8ne7.apps.googleusercontent.com',
    iosBundleId: 'com.example.animatedBottomAppBar.RunnerTests',
  );
}
